name: License Scanning for Python

on:
  pull_request:
    paths:
      - 'pyproject.toml'
      - '.github/workflows/license-scanning-python.yml'

env:
  ALLOW_LICENSES: "MIT License;Apache Software License;BSD License"
  # IGNORE_PACKAGES: ""

jobs:
  scan:
    name: Scan for licenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.2.2
      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: "3.10"
      - name: Install pip-licenses
        run: pip3 install pip-licenses
      - name: Scan for licenses
        run: pip-licenses --allow-only="${{ env.ALLOW_LICENSES }}" # --ignore-packages="${{ env.IGNORE_PACKAGES }}"