name: Linting
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ruff:
    name: Ruff Linter & Formatter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.2.2

      - name: Set up Python 3.9
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: 3.9

      - name: Install Poetry
        run: pip install poetry

      - name: Cache poetry virtualenv
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: poetry install

      - name: Cache ruff
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: .ruff_cache
          key: ${{ runner.os }}-ruff-${{ github.ref_name }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-ruff-main-${{ hashFiles('poetry.lock') }}

      - name: Run ruff formatter check
        run: poetry run ruff format --check .

      - name: Run ruff linter
        run: poetry run ruff check .
