name: pylint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: pylint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ steps.setup-python.outputs.python-version }}

      - name: Install Pylint
        run: pip install pylint

      - name: Download previous run results
        uses: dawidd6/action-download-artifact@8c96194455d424a24437ec57817e0aa1a1d72adb
        continue-on-error: true
        with:
          workflow: pylint.yaml
          workflow_conclusion: success
          name: .pylint.d
          path: /home/runner/.pylint.d
          branch: "main"

      - name: Run Pylint
        run: pylint symphony tests

      - name: Upload Pylint results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: .pylint.d
          path: ~/.pylint.d
