name: Static code analysis

on: [pull_request]

jobs:
  semgrep:
    name: run-semgrep
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.2.2
    - run: semgrep scan --error --config auto
      env:
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}